apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: default
  labels:
    app: weblog
    env: study
spec:
  containers:
    - name: debug
      image: debug:v1.0.1
      imagePullPolicy: Never
      command:
        - "sh"
        - "-c"
      args:
        - |
          while true
          do
            sleep 5
          done
